# Generated by Django 2.2.3 on 2019-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='num_good',
            field=models.IntegerField(default=1),
        ),
    ]
