# Generated by Django 2.2.3 on 2019-12-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_store_num_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='tap',
        ),
        migrations.RemoveField(
            model_name='good',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='num_good',
        ),
    ]
