# Generated by Django 2.1.7 on 2019-12-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='name',
        ),
    ]
