# Generated by Django 2.1.7 on 2019-12-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191223_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='handle_name',
        ),
    ]
