# Generated by Django 2.1.7 on 2019-12-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191223_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='icon',
        ),
    ]
